# Generated by Django 5.1.7 on 2025-03-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="post_id",
            new_name="uuid",
        ),
    ]
