# Generated by Django 5.1.7 on 2025-03-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_dislikes_remove_post_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
