# Generated by Django 5.1.7 on 2025-03-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_sentiment_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="sentiment_score",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
