# Generated by Django 5.1.7 on 2025-03-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_remove_post_sentiment_score_post_sentiment_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="sentiment_label",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
