# Generated by Django 5.1.7 on 2025-03-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_alter_post_sentiment_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
