# Generated by Django 5.1.7 on 2025-03-19 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_post_negative_percentage_post_neutral_percentage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="negative_percentage",
        ),
        migrations.RemoveField(
            model_name="post",
            name="neutral_percentage",
        ),
        migrations.RemoveField(
            model_name="post",
            name="positive_percentage",
        ),
        migrations.CreateModel(
            name="UserSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("positive_percentage", models.FloatField()),
                ("negative_percentage", models.FloatField()),
                ("neutral_percentage", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_sentiment",
            },
        ),
    ]
