# Generated by Django 5.1.7 on 2025-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_remove_post_negative_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="negative_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="post",
            name="neutral_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="post",
            name="positive_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name="UserSentiment",
        ),
    ]
