# Generated by Django 5.1.7 on 2025-03-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
